---
# tasks file for prepilot

- name: disable selinux
  selinux: state=disabled
  register: selinux_state

- name: reboot to enable selinux settings
  shell: sleep 2 && shutdown -r now "Ansible selinux change triggered"
  async: 1
  poll: 0
  ignore_errors: true
  when: selinux_state.changed

- name: Waiting for server to come back
  local_action: wait_for host={{ hostvars[inventory_hostname].ansible_host }} port={{ hostvars[inventory_hostname].ansible_port }} state=started delay=60 timeout=600
  become: no
  when: selinux_state.changed
# vim: ft=yaml:shiftwidth=2:tabstop=2:expandtab:softtabstop=2
