---

- name: load OSD layout
  set_fact:
    osd_layout: "{{ ceph_osd_layouts[ceph_osd_layout_map[osd_hostname].osd] | mandatory }}"

- name: add OSD with journal cache
  command: ceph-deploy --overwrite-conf osd create {{ osd_hostname }}:/dev/{{ item.device }}:/dev/{{ item.cache }}
  args:
    chdir: "{{ ceph_management_dir }}"
  with_items: "{{ osd_layout | selectattr('use_cache') | list }}"

- name: add OSD without journal cache
  command: ceph-deploy --overwrite-conf osd create {{ osd_hostname }}:/dev/{{ item.device }}
  args:
    chdir: "{{ ceph_management_dir }}"
  with_items: "{{ osd_layout | rejectattr('use_cache') | list }}"

- name: calculate pg number
  set_fact:
    pg_num: "{{ 100 * osd_layout | length / groups.OSD | length }}"

- debug: var=pg_num
# vim: ft=yaml:shiftwidth=2:tabstop=2:expandtab:softtabstop=2
