---
# This task used to download admin keyring file to local /tmp
#
- name: Download admin keysring file to local /tmp
  fetch: src=/etc/ceph/ceph.client.admin.keyring dest=/tmp
#
# vim: ft=yaml:shiftwidth=2:tabstop=2:expandtab:softtabstop=2
