---
# tasks file for kickoff

- include: create-config.yml

- include: zap-disk.yml
  with_items: "{{ groups.OSD }}"
  loop_control:
    loop_var: osd_hostname

- include: add-osd.yml
  with_items: "{{ groups.OSD }}"
  loop_control:
    loop_var: osd_hostname

- include: restart-mon.yml
  with_items: "{{ groups.MON }}"
  loop_control:
    loop_var: mon_hostname

- include: config-pg.yml

- include: verify.yml

# When deploy openstack we need admin keyring
- include: download_admin_keyring.yml

# vim: ft=yaml:shiftwidth=2:tabstop=2:expandtab:softtabstop=2
