---
# tasks file for kickoff

# create monitors
- include: create-mon.yml

- include: zap-disk.yml
  with_items: "{{ groups.OSD }}"
  loop_control:
    loop_var: osd_hostname

- include: add-osd.yml
  with_items: "{{ groups.OSD }}"
  loop_control:
    loop_var: osd_hostname

- include: cleanup.yml
  with_items: "{{ groups.OSD }}"
  loop_control:
    loop_var: osd_hostname

# When deploy openstack we need admin keyring
- include: download_admin_keyring.yml

# change to none type authentication
- include: restart-mon.yml

- include: verify.yml

# vim: ft=yaml:shiftwidth=2:tabstop=2:expandtab:softtabstop=2
