---
- name: delete rbd pool
  command: ssh {{ groups.MON[0] }} "ceph osd pool delete rbd rbd --yes-i-really-really-mean-it"

- name: check ceph health
  command: ssh {{ groups.MON[0] }} "ceph health"
  register: rc
  until: rc.stdout == 'HEALTH_OK'
  retries: 10
  delay: 5
#  failed_when: "rc.stdout != 'HEALTH_OK'" 

# vim: ft=yaml:shiftwidth=2:tabstop=2:expandtab:softtabstop=2
