---

- name: check ceph health
  command: ceph health
  register: rc
  until: rc.stdout == 'HEALTH_OK'
  retries: 3
  delay: 5
#  failed_when: "rc.stdout != 'HEALTH_OK'" 

# vim: ft=yaml:shiftwidth=2:tabstop=2:expandtab:softtabstop=2
