
- name: set hostname
  hostname: name={{ inventory_hostname }}

- name: add hosts file line
  lineinfile:
    dest: /etc/hosts
    regexp: '^{{ item.value.vm_network_ip }} '
    line: |
      {{ item.value.vm_network_ip }}    {{ item.key }}
  with_dict: "{{ hostvars }}"



# vim: ft=yaml:shiftwidth=2:tabstop=2:expandtab:softtabstop=2
