- name: prompt dangourous behavior again
  pause:
    prompt: |-
      !!!!!!!! IMPORTANT !!!!!!!!
      Again, do you really want to PURGE Ceph Cluster
      will be UNRECOVERABLY DELETED after partition and format.  Are you sure to
      continue? (Enter to start for real, press CTRL-C then A to abort)


- name: purge cluster
  command: "ceph-deploy purge {{ groups['EXT'] | join(' ') }}"
  when: "inventory_hostname in groups.ADMIN"

- name: purgedata cluster
  command: "ceph-deploy purgedata {{ groups['EXT'] | join(' ') }}"
  when: "inventory_hostname in groups.ADMIN"

