---

- name: install pip packages
  yum: name=python-pip state=latest

- name: install ceph-deploy packages
  pip: name=ceph_deploy version=1.5.34

- include: purgecluster.yml
  when: step_switch.purge

# vim: ft=yaml:shiftwidth=2:tabstop=2:expandtab:softtabstop=2
