---
# tasks file for install-ceph-deploy
#- name: install ceph-deploy
#  yum:
#    state: present
#    name: ceph-deploy

- name: install ceph-deploy
  yum: name="{{CEPH_DPLOY_RPM_URL}}"

- include: purgecluster.yml

# vim: ft=yaml:shiftwidth=2:tabstop=2:expandtab:softtabstop=2
