---
# tasks file for install

#- name: install python argparse from pip
#  pip:
#    state: present
#    name: "{{ item }}"
#    extra_args: "-i https://{{ PIP_REPO_MIRROR_HOST }}/simple"
#  with_items:
#    - argparse

- name: ceph-deploy install slave node
  command: "ceph-deploy install --no-adjust-repos {{ groups['all'] | join(' ') }}"
  when: ansible_hostname in "{{ groups['ADMIN'] }}"
  
