# update config to keep crushmap update after restarting osds
#
- name: update config to keep crushmap update
  shell: ssh {{ osd_hostname }} "sed -i '/rbd_cache = false/a osd_crush_update_on_start = false' /etc/ceph/ceph.conf"
  with_items: "{{ groups.OSD }}"
  loop_control:
    loop_var: osd_hostname
  
