# create ceph config for different pools according to disk type on clients

- name: get ceph cluster fsid from existing ceph.conf
  shell: ceph -s | grep -E "cluster " | awk '{print $NF}'
  register: ceph_cluster_id
  failed_when: "ceph_cluster_id.stdout | length < 36"

- name: upload config for different backends
  template:
    backup: yes
    src: ceph.conf-{{ item }}.j2
    dest: /etc/ceph/ceph-{{ item }}.conf
  with_items: "{{ types | unique | list}}"
